services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 9000:80
    links:
      - mysql
    networks:
      - internal

#Docker Networks
networks:
  internal:
    driver: bridge
